We created a little program with four nested try-blocks.
First we initialize our new object, a string.
Inside the inner try-block we print the address of the object and we throw it. Then we catach the object in the catch-handler and print it's address. Here we can prove that the addresses are different and therefore a copy of the object has been created.
In the following inner try-block, we make an emty throw and print the address of the object catched in the catch-handler. Here we can prove that the address is the same as the copy. We prove that an empty throw sends the same exception that has received.
Next, we make another empty throw, but now we catch the exception by reference and we print the address. We can see a totally different address since this one is now the address referencing the copy.
Finally in the outer try-block, we catch the object again, and print it's address. Now we can see that no more than one copy of the object has been created. If we keep throwing the exception we will always get the same address.


The output of the program can be checked at the out.txt file.
